// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-PFZCx92TKdr-QRR0gnzgpJ33fG7hefI',
    appId: '1:651482898221:web:5ac9fd546e6c91b820fda4',
    messagingSenderId: '651482898221',
    projectId: 'skinvision-ai-b3572',
    authDomain: 'skinvision-ai-b3572.firebaseapp.com',
    storageBucket: 'skinvision-ai-b3572.firebasestorage.app',
    measurementId: 'G-WYTMRQRY9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7X3Svjd5EUXEbFAYq-zyZwaXu-mnC27c',
    appId: '1:651482898221:android:17debb93a65dc91f20fda4',
    messagingSenderId: '651482898221',
    projectId: 'skinvision-ai-b3572',
    storageBucket: 'skinvision-ai-b3572.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR2I-lWbd7GyWixRVwuv3mWX8spdtV9Zk',
    appId: '1:651482898221:ios:c47ea9a7f51eb07e20fda4',
    messagingSenderId: '651482898221',
    projectId: 'skinvision-ai-b3572',
    storageBucket: 'skinvision-ai-b3572.firebasestorage.app',
    iosBundleId: 'com.example.skinvisionAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR2I-lWbd7GyWixRVwuv3mWX8spdtV9Zk',
    appId: '1:651482898221:ios:c47ea9a7f51eb07e20fda4',
    messagingSenderId: '651482898221',
    projectId: 'skinvision-ai-b3572',
    storageBucket: 'skinvision-ai-b3572.firebasestorage.app',
    iosBundleId: 'com.example.skinvisionAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-PFZCx92TKdr-QRR0gnzgpJ33fG7hefI',
    appId: '1:651482898221:web:21c2b401863d832020fda4',
    messagingSenderId: '651482898221',
    projectId: 'skinvision-ai-b3572',
    authDomain: 'skinvision-ai-b3572.firebaseapp.com',
    storageBucket: 'skinvision-ai-b3572.firebasestorage.app',
    measurementId: 'G-1WY0CJ415Q',
  );
}
